spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dongsung
    username: root
    password: 641714
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Seoul

naver:
  client-id: 'FvadT3Ycf51hJ7DHEqk2'
  client-secret: 'jF2MwAHiTa'
  scope: name,email,nickname
  client-name: Naver
  authorization-grant-type: authorization_code
  redirect-uri: http://localhost:8080/login/oauth2/code/naver

provider:
  naver:
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    user-name-attribute: response

kakao:
  client-id: "1ea96dd040d59d0fe987f530c4755afb"
  redirect-uri: http://localhost:8080/oauth/kakao/redirect

cors:
  allowedOrigins:
   - http://localhost:3000

jwt:
  secret: 6c6a4b2c6d4e7f7d2c6f7b8c7a6d6e5f7d2b7c5e4d3f2b6d7f2b4a6d5e3f2b6c6c6a4b2c6d4e7f7d2c6f7b8c7a6d6e5f7d2b7c5e4d3f2b6d7f2b4a6d5e3f2b6c
  expiration: 86400000  # 1 day in milliseconds