spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dongsung
    username: root
    password: 641714
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: "119937259413-frpeqo3l892pu2pi9s01kt9j965nptam.apps.googleusercontent.com"
            client-secret: "jF2MwAHiTa"
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
cors:
  allowedOrigins: http://localhost:3000
