spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dongsung
    username: root
    password: 641714
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 'FvadT3Ycf51hJ7DHEqk2'
            client-secret: 'jF2MwAHiTa'
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
cors:
  allowedOrigins: http://localhost:3000
